# fake_pysfm.pyi
# Autogenerated fake stub for testing
# pyre-ignore-all-errors[24]
from typing import Dict, List, Set, Tuple
import opensfm.pybundle
import opensfm.pygeometry
import opensfm.pymap

__all__ = [
    "BAHelpers",
    "StaticExtensionLoader",
    "add_connections",
    "count_tracks_per_shot",
    "filter_badly_conditioned_points",
    "realign_maps",
    "remove_connections",
    "remove_isolated_points",
]

class BAHelpers:
    @staticmethod
    def add_gcp_to_bundle(
        arg0: opensfm.pybundle.BundleAdjuster,
        arg1: opensfm.pymap.Map,
        arg2: List[opensfm.pymap.GroundControlPoint],
        arg3: Dict,
    ) -> int: ...

    @staticmethod
    def bundle(
        arg0: opensfm.pymap.Map,
        arg1: Dict[str, opensfm.pygeometry.Camera],
        arg2: Dict[str, opensfm.pymap.RigCamera],
        arg3: List[opensfm.pymap.GroundControlPoint],
        arg4: Dict,
    ) -> Dict: ...

    @staticmethod
    def bundle_local(
        arg0: opensfm.pymap.Map,
        arg1: Dict[str, opensfm.pygeometry.Camera],
        arg2: Dict[str, opensfm.pymap.RigCamera],
        arg3: List[opensfm.pymap.GroundControlPoint],
        arg4: str,
        arg5: Dict,
    ) -> Tuple: ...

    @staticmethod
    def bundle_shot_poses(
        arg0: opensfm.pymap.Map,
        arg1: Set[str],
        arg2: Dict[str, opensfm.pygeometry.Camera],
        arg3: Dict[str, opensfm.pymap.RigCamera],
        arg4: Dict,
    ) -> Dict: ...

    @staticmethod
    def bundle_to_map(
        arg0: opensfm.pybundle.BundleAdjuster,
        arg1: opensfm.pymap.Map,
        arg2: bool
    ) -> None: ...

    @staticmethod
    def detect_alignment_constraints(
        arg0: opensfm.pymap.Map,
        arg1: Dict,
        arg2: List[opensfm.pymap.GroundControlPoint],
    ) -> str: ...

    @staticmethod
    def shot_neighborhood_ids(
        arg0: opensfm.pymap.Map,
        arg1: str,
        arg2: int,
        arg3: int,
        arg4: int
    ) -> Tuple[Set[str], Set[str]]: ...

class StaticExtensionLoader:
    pass

def add_connections(
    arg0: opensfm.pymap.TracksManager,
    arg1: str,
    arg2: List[str]
) -> None: ...

def count_tracks_per_shot(
    arg0: opensfm.pymap.TracksManager,
    arg1: List[str],
    arg2: List[str]
) -> Dict[str, int]: ...

def filter_badly_conditioned_points(
    map: opensfm.pymap.Map,
    min_angle_deg: float = 1.0,
    min_abs_det: float = 1e-15
) -> int: ...

def realign_maps(
    arg0: opensfm.pymap.Map,
    arg1: opensfm.pymap.Map,
    arg2: bool
) -> None: ...

def remove_connections(
    arg0: opensfm.pymap.TracksManager,
    arg1: str,
    arg2: List[str]
) -> None: ...

def remove_isolated_points(
    map: opensfm.pymap.Map,
    k: int = 7
) -> int: ...