# # fake_opensfm.pyi
# # Autogenerated fake stub for testing
# from typing import Dict, List, Optional, Tuple, Iterator, Set
# import numpy

# class BiasView:
#     def __init__(self, arg0: "Map"): ...
#     def __contains__(self, arg0: str) -> bool: ...
#     def __getitem__(self, arg0: str) -> "opensfm.pygeometry.Similarity": ...
#     def __iter__(self) -> Iterator: ...
#     def __len__(self) -> int: ...
#     def get(self, arg0: str) -> "opensfm.pygeometry.Similarity": ...
#     def items(self) -> Iterator: ...
#     def keys(self) -> Iterator: ...
#     def values(self) -> Iterator: ...

# class CameraView:
#     def __init__(self, arg0: "Map"): ...
#     def __contains__(self, arg0: str) -> bool: ...
#     def __getitem__(self, arg0: str) -> "opensfm.pygeometry.Camera": ...
#     def __iter__(self) -> Iterator: ...
#     def __len__(self) -> int: ...
#     def get(self, arg0: str) -> "opensfm.pygeometry.Camera": ...
#     def items(self) -> Iterator: ...
#     def keys(self) -> Iterator: ...
#     def values(self) -> Iterator: ...

# class Depth:
#     value: float
#     is_radial: bool
#     std_deviation: float
#     def __init__(self, value: float, is_radial: bool, std_deviation: float): ...

# class ErrorType:
#     name: str
#     value: int
#     Pixel: "ErrorType"
#     Normalized: "ErrorType"
#     Angular: "ErrorType"
#     __members__: Dict[str, "ErrorType"]

# class GroundControlPoint:
#     id: str
#     lla: Dict[str, float]
#     lla_vec: numpy.ndarray
#     observations: List["GroundControlPointObservation"]
#     role: "GroundControlPointRole"
#     survey_point_id: int
#     has_altitude: bool
#     def __init__(self): ...
#     def add_observation(self, arg0: "GroundControlPointObservation"): ...

# class GroundControlPointObservation:
#     shot_id: str
#     projection: numpy.ndarray
#     uid: int
#     def __init__(self, arg0: Optional[str] = None, arg1: Optional[numpy.ndarray] = None): ...

# class GroundControlPointRole:
#     name: str
#     value: int
#     OPTIMIZATION: "GroundControlPointRole"
#     METRICS_ONLY: "GroundControlPointRole"
#     __members__: Dict[str, "GroundControlPointRole"]

# class Landmark:
#     id: str
#     coordinates: numpy.ndarray
#     color: numpy.ndarray
#     reprojection_errors: Dict[str, numpy.ndarray]
#     def __init__(self, arg0: str, arg1: numpy.ndarray): ...
#     def get_observations(self) -> Dict["Shot", int]: ...
#     def number_of_observations(self) -> int: ...

# class Map:
#     def __init__(self): ...
#     def add_observation(self, shot, landmark, observation): ...
#     def clean_landmarks_below_min_observations(self, arg0: int): ...
#     def clear_observations_and_landmarks(self): ...
#     def get_shots(self) -> "ShotView": ...
#     def get_cameras(self) -> "CameraView": ...
#     def get_landmarks(self) -> "LandmarkView": ...
#     def to_tracks_manager(self) -> "TracksManager": ...
#     # ... add other methods as needed with "..." body

# class Observation:
#     point: numpy.ndarray
#     color: numpy.ndarray
#     scale: float
#     segmentation: int
#     instance: int
#     depth_prior: Optional[Depth]
#     id: int
#     def __init__(self, x: float, y: float, s: float, r: int, g: int, b: int, feature: int,
#                  segmentation: int = -1, instance: int = -1): ...
#     def copy(self) -> "Observation": ...

# # Define other classes similarly...
# class Shot: ...
# class ShotMeasurements: ...
# class ShotMeasurementDouble: ...
# class ShotMeasurementInt: ...
# class ShotMeasurementString: ...
# class ShotMeasurementVec3d: ...
# class ShotMesh: ...
# class ShotView: ...
# class LandmarkView: ...
# class RigCamera: ...
# class RigCameraView: ...
# class RigInstance: ...
# class RigInstanceView: ...
# class PanoShotView: ...
# class TracksManager: ...

# Angular = ErrorType
# Normalized = ErrorType
# Pixel = ErrorType
# OPTIMIZATION = GroundControlPointRole
# METRICS_ONLY = GroundControlPointRole

"""
Pure Python implementation of pymap module.
Replaces the C++ pybind11 bindings from pymap.cc and map.cc.
"""

from __future__ import annotations
import copy
from typing import Dict, List, Optional, Tuple, Iterator
import numpy as np
from numpy.typing import NDArray


def _make_default_pose():
    from myOSfM.stub_files.pygeometry import Pose as _Pose
    return _Pose()
# ---------------------------------------------------------------------------
# Default Pose stub (dùng khi chưa có pose thực từ pygeometry)
# ---------------------------------------------------------------------------

# class _DefaultPose:
#     """Minimal Pose stub để tránh NoneType khi pose chưa được set."""
#     def __init__(self):
#         self.rotation    = np.zeros(3, dtype=np.float64)
#         self.translation = np.zeros(3, dtype=np.float64)

#     def get_rotation_matrix(self) -> np.ndarray:
#         # Rodrigues: rotation vector -> matrix
#         angle = np.linalg.norm(self.rotation)
#         if angle < 1e-10:
#             return np.eye(3, dtype=np.float64)
#         axis = self.rotation / angle
#         K = np.array([
#             [0,       -axis[2],  axis[1]],
#             [axis[2],  0,       -axis[0]],
#             [-axis[1], axis[0],  0      ]
#         ], dtype=np.float64)
#         return np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)

#     def get_origin(self) -> np.ndarray:
#         R = self.get_rotation_matrix()
#         return -(R.T @ self.translation)

#     def set_origin(self, origin) -> None:
#         R = self.get_rotation_matrix()
#         self.translation = -R @ np.array(origin, dtype=np.float64)

#     def transform(self, point: np.ndarray) -> np.ndarray:
#         R = self.get_rotation_matrix()
#         return R @ np.array(point, dtype=np.float64) + self.translation

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ErrorType:
    Pixel = None
    Normalized = None
    Angular = None

    def __init__(self, name: str, value: int):
        self.name = name
        self.value = value

    def __repr__(self):
        return f"ErrorType.{self.name}"

ErrorType.Pixel      = ErrorType("Pixel", 0)
ErrorType.Normalized = ErrorType("Normalized", 1)
ErrorType.Angular    = ErrorType("Angular", 2)
ErrorType.__members__ = {
    "Pixel": ErrorType.Pixel,
    "Normalized": ErrorType.Normalized,
    "Angular": ErrorType.Angular,
}

Pixel      = ErrorType.Pixel
Normalized = ErrorType.Normalized
Angular    = ErrorType.Angular


class GroundControlPointRole:
    OPTIMIZATION  = None
    METRICS_ONLY  = None

    def __init__(self, name: str, value: int):
        self.name = name
        self.value = value

    def __repr__(self):
        return f"GroundControlPointRole.{self.name}"

GroundControlPointRole.OPTIMIZATION = GroundControlPointRole("OPTIMIZATION", 0)
GroundControlPointRole.METRICS_ONLY = GroundControlPointRole("METRICS_ONLY", 1)
GroundControlPointRole.__members__ = {
    "OPTIMIZATION": GroundControlPointRole.OPTIMIZATION,
    "METRICS_ONLY":  GroundControlPointRole.METRICS_ONLY,
}

OPTIMIZATION = GroundControlPointRole.OPTIMIZATION
METRICS_ONLY = GroundControlPointRole.METRICS_ONLY


# ---------------------------------------------------------------------------
# Depth
# ---------------------------------------------------------------------------

class Depth:
    """Depth prior attached to an Observation."""

    def __init__(self, value: float, is_radial: bool, std_deviation: float):
        self.value         = float(value)
        self.is_radial     = bool(is_radial)
        self.std_deviation = float(std_deviation)

    def __repr__(self):
        return (f"Depth(value={self.value}, is_radial={self.is_radial}, "
                f"std_deviation={self.std_deviation})")


# ---------------------------------------------------------------------------
# Observation
# ---------------------------------------------------------------------------

class Observation:
    """One feature observation in one image."""

    NO_SEMANTIC_VALUE: int = -1

    def __init__(
        self,
        x: float, y: float, s: float,
        r: int, g: int, b: int,
        feature: int,
        segmentation: int = -1,
        instance: int = -1,
    ):
        self.point       = np.array([x, y], dtype=np.float64)
        self.scale       = float(s)
        self.color       = np.array([r, g, b], dtype=np.int32)
        self.id          = int(feature)        # feature_id
        self.segmentation = int(segmentation)
        self.instance    = int(instance)
        self.depth_prior: Optional[Depth] = None

    def copy(self) -> "Observation":
        obs = Observation(
            self.point[0], self.point[1], self.scale,
            int(self.color[0]), int(self.color[1]), int(self.color[2]),
            self.id, self.segmentation, self.instance,
        )
        obs.depth_prior = copy.copy(self.depth_prior)
        return obs

    def __repr__(self):
        return (f"Observation(point={self.point}, scale={self.scale}, "
                f"color={self.color}, id={self.id})")


# ---------------------------------------------------------------------------
# ShotMeasurement (generic optional-value wrapper)
# ---------------------------------------------------------------------------

class _ShotMeasurement:
    """Generic optional-value container — mirrors OptionalValue<T>."""

    def __init__(self):
        self._has_value = False
        self._value     = None

    @property
    def has_value(self) -> bool:
        return self._has_value

    @property
    def value(self):
        if not self._has_value:
            raise RuntimeError("ShotMeasurement has no value")
        return self._value

    @value.setter
    def value(self, v):
        self._value     = v
        self._has_value = True

    def reset(self):
        self._has_value = False
        self._value     = None

    def __repr__(self):
        return f"{self.__class__.__name__}(has_value={self._has_value}, value={self._value})"


class ShotMeasurementInt(_ShotMeasurement):
    pass

class ShotMeasurementDouble(_ShotMeasurement):
    pass

class ShotMeasurementVec3d(_ShotMeasurement):
    pass

class ShotMeasurementString(_ShotMeasurement):
    pass


# ---------------------------------------------------------------------------
# ShotMeasurements
# ---------------------------------------------------------------------------

class ShotMeasurements:
    """Bundle of optional per-shot metadata."""

    def __init__(self):
        self.gps_accuracy    = ShotMeasurementDouble()
        self.gps_position    = ShotMeasurementVec3d()
        self.orientation     = ShotMeasurementInt()
        self.capture_time    = ShotMeasurementDouble()
        self.gravity_down    = ShotMeasurementVec3d()
        self.compass_angle   = ShotMeasurementDouble()
        self.compass_accuracy = ShotMeasurementDouble()
        self.opk_angles      = ShotMeasurementVec3d()
        self.opk_accuracy    = ShotMeasurementDouble()
        self.sequence_key    = ShotMeasurementString()
        self._attributes: dict = {}

    def get_attributes(self) -> dict:
        return self._attributes

    def set_attributes(self, attrs: dict):
        self._attributes = dict(attrs)

    attributes = property(get_attributes, set_attributes)

    def set(self, other: "ShotMeasurements"):
        """Copy all values from another ShotMeasurements."""
        for field in ("gps_accuracy", "gps_position", "orientation",
                      "capture_time", "gravity_down", "compass_angle",
                      "compass_accuracy", "opk_angles", "opk_accuracy",
                      "sequence_key"):
            src = getattr(other, field)
            dst = getattr(self, field)
            if src.has_value:
                dst.value = copy.deepcopy(src.value)
            else:
                dst.reset()
        self._attributes = copy.deepcopy(other._attributes)

    def __copy__(self):
        new = ShotMeasurements()
        new.set(self)
        return new


# ---------------------------------------------------------------------------
# ShotMesh
# ---------------------------------------------------------------------------

class ShotMesh:
    def __init__(self):
        self._faces:    List = []
        self._vertices: List = []

    @property
    def faces(self):
        return self._faces

    @faces.setter
    def faces(self, v):
        self._faces = v

    @property
    def vertices(self):
        return self._vertices

    @vertices.setter
    def vertices(self, v):
        self._vertices = v


# ---------------------------------------------------------------------------
# RigCamera
# ---------------------------------------------------------------------------

class RigCamera:
    def __init__(self, pose=None, id: str = ""):
        self.id   = id
        self.pose = pose if pose is not None else _make_default_pose()

    def __repr__(self):
        return f"RigCamera(id={self.id!r})"


# ---------------------------------------------------------------------------
# RigInstance
# ---------------------------------------------------------------------------

class RigInstance:
    def __init__(self, instance_id):
        self.id            = instance_id
        self._shots:       Dict[str, "Shot"]     = {}
        self._rig_cameras: Dict[str, RigCamera]  = {}
        self.pose = _make_default_pose()   # ← không còn None

    def get_shots(self) -> Dict[str, "Shot"]:
        return self._shots

    def get_rig_cameras(self) -> Dict[str, RigCamera]:
        return self._rig_cameras

    shots       = property(get_shots)
    rig_cameras = property(get_rig_cameras)

    def keys(self) -> List[str]:
        return list(self._shots.keys())

    def add_shot(self, shot_id: str, shot: "Shot"):
        self._shots[shot_id] = shot

    def remove_shot(self, shot_id: str):
        self._shots.pop(shot_id, None)

    def update_instance_pose_with_shot(self, shot_id: str, pose):
        if pose is not None:
            self.pose = copy.copy(pose)
        elif self.pose is None:
            self.pose = _make_default_pose()

    def update_rig_camera_pose(self, rig_camera_id: str, pose):
        if rig_camera_id in self._rig_cameras:
            self._rig_cameras[rig_camera_id].pose = copy.copy(pose)

    @property
    def rig_camera_ids(self) -> Dict[str, str]:
        return {sid: rc.id for sid, rc in self._rig_cameras.items()}

    @property
    def camera_ids(self) -> Dict[str, str]:
        return {sid: shot.camera.id
                for sid, shot in self._shots.items()
                if shot.camera is not None}

    def __repr__(self):
        return f"RigInstance(id={self.id!r}, shots={list(self._shots.keys())})"


# ---------------------------------------------------------------------------
# Shot
# ---------------------------------------------------------------------------

class Shot:
    def __init__(self, shot_id: str, camera=None, rig_instance: Optional[RigInstance] = None,
                 rig_camera: Optional[RigCamera] = None, pose=None):
        self.id           = shot_id
        self.camera       = camera
        self._rig_instance = rig_instance
        self._rig_camera   = rig_camera
        self.pose         = pose
        self.mesh         = ShotMesh()
        self._metadata    = ShotMeasurements()
        self._covariance: Optional[np.ndarray] = None
        self.merge_cc     = 0
        self.scale        = 1.0
        # landmark_id -> (Observation, Landmark)
        self._landmark_observations: Dict[str, Tuple[Observation, "Landmark"]] = {}

    # --- rig accessors -------------------------------------------------------

    def get_rig_instance(self) -> Optional[RigInstance]:
        return self._rig_instance

    def get_rig_camera(self) -> Optional[RigCamera]:
        return self._rig_camera

    @property
    def rig_instance_id(self):
        return self._rig_instance.id if self._rig_instance else None

    @property
    def rig_camera_id(self):
        return self._rig_camera.id if self._rig_camera else None
    
    @property
    def rig_camera(self):
        return self._rig_camera

    @property  
    def rig_instance(self):
        return self._rig_instance

    def set_rig(self, rig_instance: RigInstance, rig_camera: RigCamera):
        self._rig_instance = rig_instance
        self._rig_camera   = rig_camera

    # --- metadata / pose -----------------------------------------------------

    @property
    def metadata(self) -> ShotMeasurements:
        return self._metadata

    @metadata.setter
    def metadata(self, v: ShotMeasurements):
        self._metadata = v

    @property
    def covariance(self):
        return self._covariance

    @covariance.setter
    def covariance(self, v):
        self._covariance = v

    # --- observations --------------------------------------------------------

    def create_observation(self, landmark: "Landmark", obs: Observation):
        self._landmark_observations[landmark.id] = (obs, landmark)

    def get_observation(self, feature_id: int) -> Optional[Observation]:
        for obs, lm in self._landmark_observations.values():
            if obs.id == feature_id:
                return obs
        return None

    def get_landmark_observation(self, landmark: "Landmark") -> Optional[Observation]:
        entry = self._landmark_observations.get(landmark.id)
        return entry[0] if entry else None

    def get_observation_landmark(self, feature_id: int) -> Optional["Landmark"]:
        for obs, lm in self._landmark_observations.values():
            if obs.id == feature_id:
                return lm
        return None

    def remove_landmark_observation(self, feature_id: int):
        to_del = [lid for lid, (obs, _) in self._landmark_observations.items()
                  if obs.id == feature_id]
        for lid in to_del:
            del self._landmark_observations[lid]

    def get_landmark_observations(self) -> Dict["Landmark", int]:
        return {lm: obs.id for obs, lm in self._landmark_observations.values()}

    def compute_valid_landmarks(self) -> List["Landmark"]:
        return [lm for _, lm in self._landmark_observations.values()]

    # --- projection (delegates to camera) ------------------------------------

    def project(self, point3d: np.ndarray) -> np.ndarray:
        if self.camera is None or self.pose is None:
            raise RuntimeError("Shot has no camera or pose")
        return self.camera.project(self.pose.transform(point3d))

    def project_many(self, points3d: np.ndarray) -> np.ndarray:
        return np.array([self.project(p) for p in points3d])

    def bearing(self, point2d: np.ndarray) -> np.ndarray:
        if self.camera is None:
            raise RuntimeError("Shot has no camera")
        return self.camera.bearing(point2d)

    def bearing_many(self, points2d: np.ndarray) -> np.ndarray:
        return np.array([self.bearing(p) for p in points2d])

    def __repr__(self):
        return f"Shot(id={self.id!r})"


# ---------------------------------------------------------------------------
# Landmark
# ---------------------------------------------------------------------------

class Landmark:
    def __init__(self, landmark_id: str, coordinates: np.ndarray):
        self.id                   = landmark_id
        self._coordinates         = np.array(coordinates, dtype=np.float64)
        self.color                = np.zeros(3, dtype=np.int32)
        self.reprojection_errors: Dict[str, np.ndarray] = {}
        # shot -> feature_id
        self._observations: Dict[Shot, int] = {}

    @property
    def coordinates(self) -> np.ndarray:
        return self._coordinates

    @coordinates.setter
    def coordinates(self, v: np.ndarray):
        self._coordinates = np.array(v, dtype=np.float64)

    def get_global_pos(self) -> np.ndarray:
        return self._coordinates

    def set_global_pos(self, pos: np.ndarray):
        self._coordinates = np.array(pos, dtype=np.float64)

    def add_observation(self, shot: Shot, feature_id: int):
        self._observations[shot] = feature_id

    def remove_observation(self, shot: Shot):
        self._observations.pop(shot, None)

    def get_observations(self) -> Dict[Shot, int]:
        return self._observations

    def number_of_observations(self) -> int:
        return len(self._observations)

    def get_observation_id_in_shot(self, shot: Shot) -> Optional[int]:
        return self._observations.get(shot)

    def clear_observations(self):
        self._observations.clear()

    def __repr__(self):
        return f"Landmark(id={self.id!r}, coords={self._coordinates})"


# ---------------------------------------------------------------------------
# GroundControlPoint / GroundControlPointObservation
# ---------------------------------------------------------------------------

class GroundControlPointObservation:
    def __init__(self, shot_id: Optional[str] = None,
                 projection: Optional[np.ndarray] = None):
        self.shot_id    = shot_id or ""
        self.projection = projection if projection is not None else np.zeros(2)
        self.uid        = 0


class GroundControlPoint:
    def __init__(self):
        self.id               = ""
        self.survey_point_id  = 0
        self.has_altitude     = False
        self.lla: Dict[str, float] = {}
        self._lla_vec         = np.zeros(3, dtype=np.float64)
        self.role             = GroundControlPointRole.OPTIMIZATION
        self._observations: List[GroundControlPointObservation] = []

    @property
    def lla_vec(self) -> np.ndarray:
        return self._lla_vec

    @lla_vec.setter
    def lla_vec(self, v: np.ndarray):
        self._lla_vec = np.array(v, dtype=np.float64)
        if len(v) >= 3:
            self.lla = {"latitude": v[0], "longitude": v[1], "altitude": v[2]}

    @property
    def observations(self) -> List[GroundControlPointObservation]:
        return self._observations

    @observations.setter
    def observations(self, v: List[GroundControlPointObservation]):
        self._observations = list(v)

    def add_observation(self, obs: GroundControlPointObservation):
        self._observations.append(obs)


# ---------------------------------------------------------------------------
# TracksManager
# ---------------------------------------------------------------------------

class TracksManager:
    """
    Manages the bipartite graph between shots and tracks (landmarks).
    Each cell is an Observation.
    """

    def __init__(self):
        # shot_id -> {track_id -> Observation}
        self._shot_to_obs:  Dict[str, Dict[str, Observation]] = {}
        # track_id -> {shot_id -> Observation}
        self._track_to_obs: Dict[str, Dict[str, Observation]] = {}

    # --- mutation ------------------------------------------------------------

    def add_observation(self, shot_id: str, track_id: str, obs: Observation):
        self._shot_to_obs.setdefault(shot_id, {})[track_id]  = obs
        self._track_to_obs.setdefault(track_id, {})[shot_id] = obs

    def remove_observation(self, shot_id: str, track_id: str):
        self._shot_to_obs.get(shot_id, {}).pop(track_id, None)
        self._track_to_obs.get(track_id, {}).pop(shot_id, None)

    # --- queries -------------------------------------------------------------

    def num_shots(self) -> int:
        return len(self._shot_to_obs)

    def num_tracks(self) -> int:
        return len(self._track_to_obs)

    def get_shot_ids(self) -> List[str]:
        return list(self._shot_to_obs.keys())

    def get_track_ids(self) -> List[str]:
        return list(self._track_to_obs.keys())

    def get_observation(self, shot_id: str, track_id: str) -> Observation:
        try:
            return self._shot_to_obs[shot_id][track_id]
        except KeyError:
            raise RuntimeError(f"No observation for shot={shot_id} track={track_id}")

    def get_shot_observations(self, shot_id: str) -> Dict[str, Observation]:
        if shot_id not in self._shot_to_obs:
            raise RuntimeError(f"Shot {shot_id!r} not in TracksManager")
        return dict(self._shot_to_obs[shot_id])

    def get_track_observations(self, track_id: str) -> Dict[str, Observation]:
        if track_id not in self._track_to_obs:
            raise RuntimeError(f"Track {track_id!r} not in TracksManager")
        return dict(self._track_to_obs[track_id])

    def get_all_pairs_connectivity(
        self,
        shots: Optional[List[str]] = None,
        tracks: Optional[List[str]] = None,
    ) -> Dict[Tuple[str, str], int]:
        """Return {(im1, im2): number_of_common_tracks}."""
        use_shots  = set(shots)  if shots  else set(self._shot_to_obs)
        use_tracks = set(tracks) if tracks else set(self._track_to_obs)

        pair_count: Dict[Tuple[str, str], int] = {}
        for track_id in use_tracks:
            shots_in_track = [s for s in self._track_to_obs.get(track_id, {})
                              if s in use_shots]
            for i in range(len(shots_in_track)):
                for j in range(i + 1, len(shots_in_track)):
                    a, b = sorted([shots_in_track[i], shots_in_track[j]])
                    pair_count[(a, b)] = pair_count.get((a, b), 0) + 1
        return pair_count

    def get_all_common_observations(
        self, im1: str, im2: str
    ) -> List[Tuple[str, Observation, Observation]]:
        """Return [(track_id, obs_in_im1, obs_in_im2), ...]."""
        obs1 = self._shot_to_obs.get(im1, {})
        obs2 = self._shot_to_obs.get(im2, {})
        result = []
        for track_id, o1 in obs1.items():
            if track_id in obs2:
                result.append((track_id, o1, obs2[track_id]))
        return result

    def construct_sub_tracks_manager(
        self, shots: List[str], tracks: List[str]
    ) -> "TracksManager":
        sub = TracksManager()
        shot_set  = set(shots)
        track_set = set(tracks)
        for shot_id in shot_set:
            for track_id, obs in self._shot_to_obs.get(shot_id, {}).items():
                if track_id in track_set:
                    sub.add_observation(shot_id, track_id, obs)
        return sub

    def write_to_file(self, path: str):
        import csv, io as _io
        with open(path, "w", newline="") as fout:
            writer = csv.writer(fout, delimiter="\t")
            for shot_id, tracks in self._shot_to_obs.items():
                for track_id, obs in tracks.items():
                    writer.writerow([
                        shot_id, track_id,
                        obs.id,
                        obs.point[0], obs.point[1],
                        obs.scale,
                        obs.color[0], obs.color[1], obs.color[2],
                        obs.segmentation, obs.instance,
                    ])

    def as_string(self) -> str:
        import io as _io, csv
        buf = _io.StringIO()
        writer = csv.writer(buf, delimiter="\t")
        for shot_id, tracks in self._shot_to_obs.items():
            for track_id, obs in tracks.items():
                writer.writerow([
                    shot_id, track_id, obs.id,
                    obs.point[0], obs.point[1], obs.scale,
                    obs.color[0], obs.color[1], obs.color[2],
                    obs.segmentation, obs.instance,
                ])
        return buf.getvalue()

    @staticmethod
    def instanciate_from_file(path: str) -> "TracksManager":
        import csv
        tm = TracksManager()
        with open(path, "r", newline="") as fin:
            for row in csv.reader(fin, delimiter="\t"):
                if len(row) < 11:
                    continue
                shot_id, track_id = row[0], row[1]
                obs = Observation(
                    float(row[3]), float(row[4]), float(row[5]),
                    int(row[6]), int(row[7]), int(row[8]),
                    int(row[2]),
                    int(row[9]), int(row[10]),
                )
                tm.add_observation(shot_id, track_id, obs)
        return tm

    @staticmethod
    def instanciate_from_string(data: str) -> "TracksManager":
        import csv, io as _io
        tm = TracksManager()
        for row in csv.reader(_io.StringIO(data), delimiter="\t"):
            if len(row) < 11:
                continue
            shot_id, track_id = row[0], row[1]
            obs = Observation(
                float(row[3]), float(row[4]), float(row[5]),
                int(row[6]), int(row[7]), int(row[8]),
                int(row[2]),
                int(row[9]), int(row[10]),
            )
            tm.add_observation(shot_id, track_id, obs)
        return tm

    @staticmethod
    def merge_tracks_manager(managers: List["TracksManager"]) -> "TracksManager":
        merged = TracksManager()
        for tm in managers:
            for shot_id, tracks in tm._shot_to_obs.items():
                for track_id, obs in tracks.items():
                    merged.add_observation(shot_id, track_id, obs)
        return merged

    def __repr__(self):
        return (f"TracksManager(shots={self.num_shots()}, "
                f"tracks={self.num_tracks()})")


# ---------------------------------------------------------------------------
# View helpers (read-only dict-like wrappers)
# ---------------------------------------------------------------------------

class _BaseView:
    def __init__(self, data: dict):
        self._data = data

    def __len__(self) -> int:
        return len(self._data)

    def __contains__(self, key) -> bool:
        return key in self._data

    def __getitem__(self, key):
        return self._data[key]

    def __iter__(self) -> Iterator:
        return iter(self._data)

    def get(self, key):
        return self._data.get(key)

    def items(self) -> Iterator:
        return iter(self._data.items())

    def keys(self) -> Iterator:
        return iter(self._data.keys())

    def values(self) -> Iterator:
        return iter(self._data.values())


class ShotView(_BaseView):
    pass

class PanoShotView(_BaseView):
    pass

class LandmarkView(_BaseView):
    pass

class CameraView(_BaseView):
    pass

class BiasView(_BaseView):
    pass

class RigCameraView(_BaseView):
    pass

class RigInstanceView(_BaseView):
    pass


# ---------------------------------------------------------------------------
# Map
# ---------------------------------------------------------------------------

class Map:
    """
    Central scene graph.
    Mirrors map::Map from map.cc / pymap.cc.
    """

    def __init__(self):
        self._cameras:       Dict[str, object]      = {}
        self._shots:         Dict[str, Shot]         = {}
        self._pano_shots:    Dict[str, Shot]         = {}
        self._landmarks:     Dict[str, Landmark]     = {}
        self._rig_cameras:   Dict[str, RigCamera]    = {}
        self._rig_instances: Dict[str, RigInstance]  = {}
        self._biases:        Dict[str, object]       = {}
        self._reference      = None

    # --- static deep copy ----------------------------------------------------

    @staticmethod
    def deep_copy(src: "Map", copy_observations: bool = True) -> "Map":
        dst = Map()
        dst._reference = copy.deepcopy(src._reference)

        for cam_id, cam in src._cameras.items():
            dst.create_camera(cam)

        for shot_id, shot in src._shots.items():
            dst._update_shot_with_rig(shot, is_panoshot=False)

        for shot_id, shot in src._pano_shots.items():
            dst._update_shot_with_rig(shot, is_panoshot=True)

        for lm_id, lm in src._landmarks.items():
            dst.create_landmark(lm_id, lm.get_global_pos())

        if copy_observations:
            for shot_id, shot in src._shots.items():
                for lm, feat_id in shot.get_landmark_observations().items():
                    obs = shot.get_landmark_observation(lm)
                    if obs:
                        dst.add_observation(shot_id, lm.id, obs.copy())

        for cam_id, bias in src._biases.items():
            dst._biases[cam_id] = copy.copy(bias)

        return dst

    # --- camera --------------------------------------------------------------

    def create_camera(self, camera) -> object:
        self._cameras[camera.id] = camera
        self._biases[camera.id]  = None   # placeholder for Similarity
        return self._cameras[camera.id]

    def get_camera(self, camera_id: str):
        if camera_id not in self._cameras:
            raise RuntimeError(f"Accessing invalid CameraId {camera_id}")
        return self._cameras[camera_id]

    def has_camera(self, camera_id: str) -> bool:
        return camera_id in self._cameras

    def get_camera_view(self) -> CameraView:
        return CameraView(self._cameras)

    def get_cameras(self) -> CameraView:
        return self.get_camera_view()

    # --- bias ----------------------------------------------------------------

    def set_bias(self, camera_id: str, transform):
        if camera_id not in self._biases:
            raise RuntimeError(f"Accessing invalid CameraID {camera_id}")
        self._biases[camera_id] = transform

    def get_bias(self, camera_id: str):
        if camera_id not in self._biases:
            raise RuntimeError(f"Accessing invalid CameraID {camera_id}")
        return self._biases[camera_id]

    def get_biases(self) -> BiasView:
        return BiasView(self._biases)

    # --- rig cameras ---------------------------------------------------------

    def create_rig_camera(self, rig_camera: RigCamera) -> RigCamera:
        if rig_camera.id in self._rig_cameras:
            raise RuntimeError(f"RigCamera {rig_camera.id} already exists.")
        self._rig_cameras[rig_camera.id] = rig_camera
        return self._rig_cameras[rig_camera.id]

    def has_rig_camera(self, rig_camera_id: str) -> bool:
        return rig_camera_id in self._rig_cameras

    def get_rig_camera(self, rig_camera_id: str) -> RigCamera:
        if rig_camera_id not in self._rig_cameras:
            raise RuntimeError(f"Accessing invalid RigCameraID {rig_camera_id}")
        return self._rig_cameras[rig_camera_id]

    # --- rig instances -------------------------------------------------------

    def create_rig_instance(self, instance_id) -> RigInstance:
        if instance_id in self._rig_instances:
            raise RuntimeError(f"RigInstance {instance_id} already exists.")
        ri = RigInstance(instance_id)
        self._rig_instances[instance_id] = ri
        return ri

    def update_rig_instance(self, other: RigInstance) -> RigInstance:
        if other.id not in self._rig_instances:
            raise RuntimeError("Rig instance does not exist.")
        self._rig_instances[other.id] = other
        return other

    def remove_rig_instance(self, instance_id):
        if instance_id not in self._rig_instances:
            raise RuntimeError("Rig instance does not exist.")
        del self._rig_instances[instance_id]

    def has_rig_instance(self, instance_id) -> bool:
        return instance_id in self._rig_instances

    def get_rig_instance(self, instance_id) -> RigInstance:
        if instance_id not in self._rig_instances:
            raise RuntimeError("Accessing invalid RigInstance index")
        return self._rig_instances[instance_id]

    # --- shots ---------------------------------------------------------------

    def _make_shot(self, shot_id: str, camera_id: str,
                   rig_camera_id: str, instance_id,
                   pose=None) -> Shot:
        camera       = self.get_camera(camera_id)
        rig_instance = self.get_rig_instance(instance_id)
        rig_camera   = self.get_rig_camera(rig_camera_id)
        return Shot(shot_id, camera, rig_instance, rig_camera, pose)

    def create_shot(
        self,
        shot_id: str,
        camera_id: str,
        rig_camera_id: str = None,
        instance_id: str = None,
        pose=None,
    ) -> Shot:
        rig_camera_id = rig_camera_id if rig_camera_id else camera_id
        instance_id = instance_id if instance_id else shot_id

        if rig_camera_id not in self._rig_cameras:
            self._rig_cameras[rig_camera_id] = RigCamera(id=rig_camera_id)

        if instance_id not in self._rig_instances:
            ri = RigInstance(instance_id)
            self._rig_instances[instance_id] = ri

        if shot_id in self._shots:
            raise RuntimeError(f"Shot {shot_id} already exists.")

        shot = self._make_shot(shot_id, camera_id, rig_camera_id, instance_id, pose)
        self._shots[shot_id] = shot

        return shot

    def remove_shot(self, shot_id: str):
        if shot_id not in self._shots:
            raise RuntimeError(f"Accessing invalid ShotID {shot_id}")
        shot = self._shots[shot_id]
        if shot.get_rig_instance():
            shot.get_rig_instance().remove_shot(shot_id)
        for lm in list(shot.get_landmark_observations().keys()):
            lm.remove_observation(shot)
        del self._shots[shot_id]

    def get_shot(self, shot_id: str) -> Shot:
        if shot_id not in self._shots:
            raise RuntimeError(f"Accessing invalid ShotID {shot_id}")
        return self._shots[shot_id]

    def has_shot(self, shot_id: str) -> bool:
        return shot_id in self._shots

    def update_shot(self, other_shot: Shot) -> Shot:
        if other_shot.id not in self._shots:
            raise RuntimeError(f"Shot {other_shot.id} does not exist.")
        self._update_shot_with_rig(other_shot, is_panoshot=False)
        shot = self._shots[other_shot.id]
        shot.merge_cc = other_shot.merge_cc
        shot.scale    = other_shot.scale
        shot.metadata.set(other_shot.metadata)
        shot.covariance = copy.copy(other_shot.covariance)
        return shot

    def get_shots(self) -> ShotView:
        return ShotView(self._shots)

    # --- pano shots ----------------------------------------------------------

    def create_pano_shot(self, shot_id: str, camera_id: str,
                         rig_camera_id: str, instance_id,
                         pose=None) -> Shot:
        if shot_id in self._pano_shots:
            raise RuntimeError(f"PanoShot {shot_id} already exists.")
        shot = self._make_shot(shot_id, camera_id, rig_camera_id, instance_id, pose)
        self._pano_shots[shot_id] = shot
        return shot

    def remove_pano_shot(self, shot_id: str):
        if shot_id not in self._pano_shots:
            raise RuntimeError(f"Accessing invalid ShotID {shot_id}")
        shot = self._pano_shots[shot_id]
        if shot.get_rig_instance():
            shot.get_rig_instance().remove_shot(shot_id)
        del self._pano_shots[shot_id]

    def get_pano_shot(self, shot_id: str) -> Shot:
        if shot_id not in self._pano_shots:
            raise RuntimeError(f"Accessing invalid PanoShotID {shot_id}")
        return self._pano_shots[shot_id]

    def has_pano_shot(self, shot_id: str) -> bool:
        return shot_id in self._pano_shots

    def update_pano_shot(self, other_shot: Shot) -> Shot:
        if other_shot.id not in self._pano_shots:
            raise RuntimeError(f"Pano shot {other_shot.id} does not exist.")
        self._update_shot_with_rig(other_shot, is_panoshot=True)
        return self._pano_shots[other_shot.id]

    def get_pano_shots(self) -> PanoShotView:
        return PanoShotView(self._pano_shots)

    # --- rig helper ----------------------------------------------------------

    def _update_shot_with_rig(self, other_shot: Shot, is_panoshot: bool):
        ri = other_shot.get_rig_instance()
        if ri is None:
            return
        instance_id = ri.id
        if not self.has_rig_instance(instance_id):
            self.create_rig_instance(instance_id)

        for shot_id, shot in ri.get_shots().items():
            cam = shot.camera
            if cam is not None and not self.has_camera(cam.id):
                self.create_camera(cam)

            rc = shot.get_rig_camera()
            if rc is not None and not self.has_rig_camera(rc.id):
                self.create_rig_camera(rc)

            exists = self.has_pano_shot(shot_id) if is_panoshot else self.has_shot(shot_id)
            if not exists:
                cam_id = cam.id if cam else ""
                rc_id  = rc.id  if rc  else ""
                if is_panoshot:
                    self.create_pano_shot(shot_id, cam_id, rc_id, instance_id, shot.pose)
                else:
                    self.create_shot(shot_id, cam_id, rc_id, instance_id, shot.pose)

        self.get_rig_instance(instance_id).update_instance_pose_with_shot(
            other_shot.id, other_shot.pose
        )

    # --- landmarks -----------------------------------------------------------

    def create_landmark(self, lm_id: str, global_pos: np.ndarray) -> Landmark:
        if lm_id in self._landmarks:
            raise RuntimeError(f"Landmark {lm_id} already exists.")
        lm = Landmark(lm_id, global_pos)
        self._landmarks[lm_id] = lm
        return lm

    def remove_landmark(self, lm):
        lm_id = lm.id if isinstance(lm, Landmark) else lm
        if lm_id not in self._landmarks:
            raise RuntimeError(f"Accessing invalid LandmarkId {lm_id}")
        landmark = self._landmarks[lm_id]
        for shot, feat_id in list(landmark.get_observations().items()):
            shot.remove_landmark_observation(feat_id)
        del self._landmarks[lm_id]

    def has_landmark(self, lm_id: str) -> bool:
        return lm_id in self._landmarks

    def get_landmark(self, lm_id: str) -> Landmark:
        if lm_id not in self._landmarks:
            raise RuntimeError(f"Accessing invalid LandmarkId {lm_id}")
        return self._landmarks[lm_id]

    def get_landmark_view(self) -> LandmarkView:
        return LandmarkView(self._landmarks)

    def get_landmarks(self) -> LandmarkView:
        return self.get_landmark_view()

    def clear_observations_and_landmarks(self):
        for lm in self._landmarks.values():
            for shot, feat_id in lm.get_observations().items():
                shot.remove_landmark_observation(feat_id)
            lm.clear_observations()
        self._landmarks.clear()

    def clean_landmarks_below_min_observations(self, min_observations: int):
        to_delete = [
            lm_id for lm_id, lm in self._landmarks.items()
            if lm.number_of_observations() < min_observations
        ]
        for lm_id in to_delete:
            self.remove_landmark(lm_id)

    # --- observations --------------------------------------------------------

    def add_observation(self, shot_or_id, landmark_or_id, obs: Observation):
        shot = shot_or_id if isinstance(shot_or_id, Shot) \
               else self.get_shot(shot_or_id)
        lm   = landmark_or_id if isinstance(landmark_or_id, Landmark) \
               else self.get_landmark(landmark_or_id)
        lm.add_observation(shot, obs.id)
        shot.create_observation(lm, obs)

    def remove_observation(self, shot_id: str, lm_id: str):
        shot = self.get_shot(shot_id)
        lm   = self.get_landmark(lm_id)
        feat_id = lm.get_observation_id_in_shot(shot)
        if feat_id is not None:
            shot.remove_landmark_observation(feat_id)
        lm.remove_observation(shot)

    # --- reference -----------------------------------------------------------

    # def set_reference(self, reference):
    #     self._reference = reference

    # SAU:
    def set_reference(self, lat_or_reference, lon=None, alt=None):

        if lon is None and alt is None:

            self._reference = lat_or_reference
        else:

            class _Ref:
                pass
            ref = _Ref()
            ref.lat = float(lat_or_reference)
            ref.lon = float(lon)
            ref.alt = float(alt)
            self._reference = ref

    def get_reference(self):
        return self._reference

    # --- reprojection errors -------------------------------------------------

    def compute_reprojection_errors(
        self, tracks_manager: TracksManager, error_type: ErrorType
    ) -> Dict[str, Dict[str, np.ndarray]]:
        errors: Dict[str, Dict[str, np.ndarray]] = {}
        for shot_id in tracks_manager.get_shot_ids():
            if shot_id not in self._shots:
                continue
            shot = self._shots[shot_id]
            per_shot: Dict[str, np.ndarray] = {}
            for track_id, obs in tracks_manager.get_shot_observations(shot_id).items():
                if track_id not in self._landmarks:
                    continue
                lm = self._landmarks[track_id]
                pt = lm.get_global_pos()
                if error_type == ErrorType.Pixel or error_type.value == 0:
                    per_shot[track_id] = obs.point - shot.project(pt)
                elif error_type == ErrorType.Normalized or error_type.value == 1:
                    per_shot[track_id] = (obs.point - shot.project(pt)) / obs.scale
                elif error_type == ErrorType.Angular or error_type.value == 2:
                    origin  = shot.pose.get_origin() if shot.pose else np.zeros(3)
                    pt_dir  = (pt - origin) / (np.linalg.norm(pt - origin) + 1e-10)
                    bearing = shot.bearing(obs.point)
                    bearing = bearing / (np.linalg.norm(bearing) + 1e-10)
                    angle   = np.arccos(np.clip(pt_dir.dot(bearing), -1.0, 1.0))
                    per_shot[track_id] = np.array([angle, angle])
            errors[shot_id] = per_shot
        return errors

    def get_valid_observations(
        self, tracks_manager: TracksManager
    ) -> Dict[str, Dict[str, Observation]]:
        result: Dict[str, Dict[str, Observation]] = {}
        for shot_id in tracks_manager.get_shot_ids():
            if shot_id not in self._shots:
                continue
            per_shot: Dict[str, Observation] = {}
            for track_id, obs in tracks_manager.get_shot_observations(shot_id).items():
                if track_id in self._landmarks:
                    per_shot[track_id] = obs
            result[shot_id] = per_shot
        return result

    def to_tracks_manager(self) -> TracksManager:
        tm = TracksManager()
        for shot_id, shot in {**self._shots, **self._pano_shots}.items():
            for lm, feat_id in shot.get_landmark_observations().items():
                obs = shot.get_landmark_observation(lm)
                if obs:
                    tm.add_observation(shot_id, lm.id, obs)
        return tm

    def __repr__(self):
        return (f"Map(cameras={len(self._cameras)}, shots={len(self._shots)}, "
                f"landmarks={len(self._landmarks)})")