use_exif_size: no
flann_algorithm: KDTREE
feature_process_size: 504
feature_min_frames: 10000
processes: 2
matching_gps_neighbors: 0
matching_gps_distance: 0
matching_graph_rounds: 50
optimize_camera_parameters: yes
reconstruction_algorithm: incremental
undistorted_image_format: tif
bundle_outlier_filtering_type: AUTO
sift_peak_threshold: 0.066
align_orientation_prior: vertical
triangulation_type: ROBUST
retriangulation_ratio: 2
matcher_type: FLANN
feature_type: DSPSIFT
use_altitude_tag: yes
align_method: auto
local_bundle_radius: 0